query getSubscriptionById($id: String!) {
  subscriptionById(id: $id) {
    id
    planId
    productId
    status
    dateCreated
    datePeriodEnd
    dateOrderPeriodEnd
    price
    quantity
    trial
    dateTrialEnd
    items {
      product {
        id
        name
        images {
          caption
          file {
            width
            height
            url
          }
        }
      }
      priceTotal
      quantity
      id
    }
    product {
      name
      slug
      images {
        caption
        file {
          width
          height
          url
        }
      }
    }
    variant {
      name
      id
    }
    options {
      value
    }
    subTotal
    discountTotal
    taxTotal
    grandTotal
    currency
    shipping {
      name
      address1
      address2
      city
      state
      country
      zip
      phone
      service
      serviceName
      price
    }
    billing {
      name
      address1
      address2
      city
      state
      country
      zip
      method
      card {
        brand
        last4
        expMonth
        expYear
      }
    }
    billingSchedule {
      interval
      intervalCount
      limit
      limitCurrent
    }
    orderSchedule {
      interval
      intervalCount
      limit
      limitCurrent
    }
  }
}

query getSubscriptions($currency: String) {
  subscriptions(_currency: $currency) {
    results {
      id
      status
      datePeriodEnd
      dateOrderPeriodEnd
      product {
        name
        images {
          id
          caption
          file {
            url
            width
            height
          }
        }
      }
      billingSchedule {
        interval
        intervalCount
        trialDays
      }
      orderSchedule {
        interval
        intervalCount
      }
      recurringTotal
    }
  }
}

mutation cancelSubscription($id: String) {
  updateSubscription(id: $id, input: { canceled: true }) {
    canceled
  }
}

mutation pauseSubscription($id: String, $status: Boolean, $resumeAt: DateTime) {
  updateSubscription(
    id: $id
    input: { paused: $status, datePauseEnd: $resumeAt }
  ) {
    paused
  }
}

mutation deleteSubscriptionItem($id: String, $itemId: String) {
  deleteSubscriptionItem(subscriptionId: $id, itemId: $itemId) {
    product {
      name
      id
      price
    }
    quantity
    priceTotal
  }
}

mutation addSubscriptionItem($id: String, $itemId: ID, $quantity: Int) {
  addSubscriptionItem(
    subscriptionId: $id
    input: { productId: $itemId, quantity: $quantity }
  ) {
    product {
      name
      id
      price
    }
    quantity
    priceTotal
  }
}

mutation replaceSubscriptionProduct(
  $id: String
  $productId: ID
  $variantId: ID
  $qty: Int
  $interval: String
  $intervalCount: Int
) {
  updateSubscription(
    id: $id
    input: {
      variantId: $variantId
      productId: $productId
      quantity: $qty
      options: null
      billingSchedule: { interval: $interval, intervalCount: $intervalCount }
    }
  ) {
    product {
      name
      id
      price
    }
    quantity
    trial
    grandTotal
  }
}

mutation replaceSubscriptionProductDetails(
  $id: String
  $variantId: ID
  $qty: Int
  $interval: String
  $intervalCount: Int
) {
  updateSubscription(
    id: $id
    input: {
      variantId: $variantId
      quantity: $qty
      options: null
      billingSchedule: { interval: $interval, intervalCount: $intervalCount }
    }
  ) {
    product {
      name
      id
      price
    }
    quantity
    trial
    grandTotal
  }
}
