export enum API_ROUTES {
  SIGN_UP = '/horizon-api/sign-up',
  LOGIN = '/horizon-api/login',
  LOGOUT = '/horizon-api/logout',
  SET_PASSWORD = '/horizon-api/set-password',
  PASSWORD_RECOVERY = '/horizon-api/password-recovery',
  CART = '/horizon-api/cart',
  CART_ITEMS = '/horizon-api/cart/items',
  PREVIEW = '/horizon-api/preview',
  CANCEL_SUBSCRIPTION = '/horizon-api/cancel-subscription',
  PAUSE_SUBSCRIPTION = '/horizon-api/pause-subscription',
  DELETE_INVOICE_ITEM = '/horizon-api/delete-invoice-item',
  ADD_INVOICE_ITEM = '/horizon-api/add-invoice-item',
  SEARCH_PRODUCTS = '/horizon-api/search-products',
  EDIT_SUBSCRIPTION_PLAN = '/horizon-api/edit-subscription-plan',
  EDIT_SUBSCRIPTION_PRODUCT_DETAILS = '/horizon-api/edit-subscription-product-details',
}
